# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc39351907b5953dcecd2d369c1aff05647332dcf7edd21069023836a3665cd840ca32672b63776f1d9e0d2c51c86e2bc32a51cbfd2c45c82664c54b8e9df3c3

test:
  secret_key_base: fbf05fa081611fcc37140c865a09b938ade37ed6abb5a9b1bd4b05dc655f46e18c24896cf9484205965f368c5b4fd7f97952c539d95e65f847be4e0d4e668f4f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
